project_name: statusetat
version: 2

builds:
  - id: binary
    binary: statusetat
    dir: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X github.com/prometheus/common/version.Version={{.Version}}
      - -X github.com/prometheus/common/version.Revision={{.FullCommit}}
      - -X github.com/prometheus/common/version.Branch={{.Branch}}
      - -X github.com/prometheus/common/version.BuildUser={{.Env.USER}}
      - -X github.com/prometheus/common/version.BuildDate={{.Date}}
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: archives
    ids:
      - binary
    formats: ["tar.gz"]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: true
  - id: archives-zip
    ids:
      - binary
    formats: ["zip"]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: true

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  github:
    owner: orange-cloudfoundry
    name: statusetat
  prerelease: auto
  name_template: '{{.Tag}}'